agent_id: did:hmp:f8964b4b-6dc5-45fa-933c-1f24e58e51f7
agent_name: Agent_1
agent_role: core
api_port: 8080
bootstrap_responder: true
debug: true
default_llm: local-model
default_user:
  badges: 📌
  email: user@example.com
  password: password
  username: user
dht_enabled: true
dht_update: true
enable_llm: true
global_addresses:
- any://95.79.96.23:4000
- any://195.122.229.174:4000
identity_agent: f8964b4b-6dc5-45fa-933c-1f24e58e51f7
llm_backends:
- format: gguf
  name: local-model
  path: /models/gguf/mistral.gguf
  prompt_template: mistral
  type: local
- api_key: lm-studio-any-key
  base_url: http://127.0.0.1:1234/v1
  model: mistral
  name: lmstudio-local
  provider: openai-compatible
  type: api
- api_key: sk-...
  model: gpt-4o
  name: openai-gpt4o
  provider: openai
  type: api
local_addresses:
- any://192.168.20.120:4000
- any://192.168.21.120:4000
- any://192.168.220.1:4000
- any://192.168.199.1:4000
- any://[201:ab61:1203:b973:909c:ef3:26b8:4ec2]:4000
- any://127.0.0.1:4000
log_level: INFO
notebook_ui: true
privkey: '-----BEGIN PRIVATE KEY-----

  MC4CAQAwBQYDK2VwBCIEILtCTUYQfVGaGrsB8TTK0hfGkCaL67eZH7RZDn5D5iRs

  -----END PRIVATE KEY-----

  '
proxy_address: 127.0.0.1:9050
proxy_mode: false
proxy_type: socks5
pubkey: '-----BEGIN PUBLIC KEY-----

  MCowBQYDK2VwAyEA70idbI41OtB1hmMZo25b6n9i/e9Wpatj3o/Db9ayfIo=

  -----END PUBLIC KEY-----

  '
serve_api: true
ui_hosts:
- 127.0.0.1
- ::1
ui_port: 8765
update_interval: 60
