agent_id: did:hmp:4b2e20ef-a6c1-4605-897f-665140035494
agent_name: CognitiveCore
agent_role: core
api_port: 8080
bootstrap_responder: true
debug: true
default_llm: local-model
default_user:
  badges: 📌
  email: user@example.com
  password: password
  username: user
dht_enabled: true
dht_update: true
enable_llm: true
identity_agent: 4b2e20ef-a6c1-4605-897f-665140035494
llm_backends:
- format: gguf
  name: local-model
  path: /models/gguf/mistral.gguf
  prompt_template: mistral
  type: local
- api_key: lm-studio-any-key
  base_url: http://127.0.0.1:1234/v1
  model: mistral
  name: lmstudio-local
  provider: openai-compatible
  type: api
- api_key: sk-...
  model: gpt-4o
  name: openai-gpt4o
  provider: openai
  type: api
log_level: INFO
notebook_ui: true
proxy_address: 127.0.0.1:9050
proxy_mode: false
proxy_type: socks5
serve_api: true
tcp_port: 5000
udp_port: 4000
ui_hosts:
- 127.0.0.1
- ::1
ui_port: 8765
update_interval: 60
