agent_mode: mcp                     # Режим работы: mcp / full / llm / test
agent_name: mcp-01                  # Имя агента
agent_role: core                    # или connector

llm_mode: openai                    # openai | chatgpt_session | mesh
llm_model: gpt-4
llm_api_key: sk-...
llm_api_url: https://api.openai.com/v1/chat/completions
llm_session_cookie: null
context_db: context.sqlite

# REST API
api_port: 8080                      # Порт для локального REST API
serve_api: true                     # Включить REST API (например, для мониторинга или команд)

# DHT / Mesh Connectivity
dht_enabled: true                   # Активировать DHT-модуль
dht_port: 20784                     # Порт для связи по DHT (TCP/UDP)

internal_ips:                       # Список локальных IP-адресов (для проброса или диагностики)
  - 192.168.20.10
  - 192.168.21.10

external_ips:                       # Список внешних IP-адресов (для публикации другим агентам)
  - 95.23.73.23
  - 195.134.218.134
  - "201:ab61:1205:b963:909c:eу3:26b8:4ec2"

# Bootstrap
bootstrap_file: bootstrap.txt       # Файл с начальными узлами
update_dht: true                    # Обновлять DHT периодически
update_interval: 60                # Интервал между обновлениями (сек)

# Прочее
bootstrap_responder: true          # Отвечать на запросы других агентов
enable_llm: false                  # Подключён ли внутренний ИИ (если false — только DHT-режим)
