name: Deploy to Blogger

on:
  schedule:
    - cron: "0 * * * *"   # каждый час в начале часа
  workflow_dispatch:

jobs:
  publish:
    runs-on: ubuntu-latest

    steps:
      - uses: actions/checkout@v3

      - name: Set up Python
        uses: actions/setup-python@v4
        with:
          python-version: '3.x'

      - name: Install dependencies
        run: pip install --upgrade google-api-python-client google-auth-httplib2 google-auth-oauthlib markdown2

      - name: Fetch published_posts.json from gh-pages
        run: |
          git fetch origin gh-pages
          git checkout origin/gh-pages -- published_posts.json || echo "{}" > published_posts.json

      - name: Write token.json
        run: echo "${{ secrets.TOKEN_JSON }}" | base64 --decode > token.json

      - name: Publish to Blogger
        run: python scripts/publish_to_blogger.py
        env:
          BLOG_ID: ${{ secrets.BLOGGER_BLOG_ID }}
          TOKEN_FILE: token.json

      - name: Push updated published_posts.json to gh-pages
        run: |
          TMP_DIR=$(mktemp -d)
          git clone --branch gh-pages https://x-access-token:${{ secrets.PAT_TOKEN }}@github.com/${{ github.repository }}.git "$TMP_DIR"

          cp published_posts.json "$TMP_DIR/published_posts.json"

          cd "$TMP_DIR"
          git config user.name "github-actions[bot]"
          git config user.email "github-actions[bot]@users.noreply.github.com"
          git add published_posts.json
          git commit -m "Update published_posts.json" || echo "No changes to commit"
          git push origin gh-pages
