name: Deploy HMP Spec

on:
  schedule:
    - cron: "0 * * * *"   # раз в час
  workflow_dispatch:

concurrency:
  group: "spec-deploy"
  cancel-in-progress: false

jobs:
  publish:
    runs-on: ubuntu-latest

    steps:
      - uses: actions/checkout@v3

      - name: Set up Python
        uses: actions/setup-python@v4
        with:
          python-version: '3.x'

      - name: Install dependencies
        run: pip install requests

      - name: Fetch published_spec.json from gh-spec branch (or init)
        run: |
          if git ls-remote --exit-code origin gh-spec; then
            git fetch origin gh-spec
            git checkout origin/gh-spec -- published_spec.json
          else
            echo "{}" > published_spec.json
          fi

      - name: Publish to Hashnode (spec)
        run: python scripts/publish_to_spec.py
        env:
          HASHNODE_TOKEN: ${{ secrets.HASHNODE_SPEC_TOKEN }}
          HASHNODE_PUBLICATION_ID: ${{ secrets.HASHNODE_SPEC_PUBLICATION_ID }}

      - name: Push updated published_spec.json to gh-spec
        run: |
          TMP_DIR=$(mktemp -d)
          git clone https://x-access-token:${{ secrets.PAT_TOKEN }}@github.com/${{ github.repository }}.git "$TMP_DIR"
          cd "$TMP_DIR"

          if git show-ref --quiet refs/heads/gh-spec; then
            git checkout gh-spec
          else
            git checkout --orphan gh-spec
            git rm -rf .
          fi

          cp $GITHUB_WORKSPACE/published_spec.json ./published_spec.json

          git config user.name "github-actions[bot]"
          git config user.email "github-actions[bot]@users.noreply.github.com"

          git add published_spec.json
          git commit -m "Update published_spec.json" --quiet || echo "No changes to commit"
          git push origin gh-spec --force --quiet
