name: Deploy to Blogger

on:
  schedule:
    - cron: "0 * * * *"   # каждый час в начале часа
  workflow_dispatch:       # возможность вручную запустить

jobs:
  publish:
    runs-on: ubuntu-latest

    steps:
      - uses: actions/checkout@v3

      - name: Set up Python
        uses: actions/setup-python@v4
        with:
          python-version: '3.x'

      - name: Install dependencies
        run: pip install --upgrade google-api-python-client google-auth-httplib2 google-auth-oauthlib markdown2

      - name: Write token.pkl
        run: echo "${{ secrets.TOKEN_PKL }}" | base64 --decode > token.pkl

      - name: Publish to Blogger
        run: python scripts/publish_to_blogger.py
        env:
          BLOG_ID: ${{ secrets.BLOGGER_BLOG_ID }}
          TOKEN_FILE: token.pkl

      - name: Commit updated published_posts.json
        run: |
          git config user.name "github-actions[bot]"
          git config user.email "github-actions[bot]@users.noreply.github.com"
          git add scripts/published_posts.json
          git commit -m "Update published_posts.json" || echo "No changes to commit"
          git push "https://${{ secrets.GITHUB_TOKEN }}@github.com/${{ github.repository }}.git" HEAD:main
