name: Deploy to Blogger

on:
  schedule:
    - cron: "0 * * * *"   # каждый час в начале часа
  workflow_dispatch:       # возможность вручную запустить

jobs:
  publish:
    runs-on: ubuntu-latest

    steps:
      - uses: actions/checkout@v3

      - name: Set up Python
        uses: actions/setup-python@v4
        with:
          python-version: '3.x'

      - name: Install dependencies
        run: pip install --upgrade google-api-python-client google-auth-httplib2 google-auth-oauthlib markdown2

      - name: Write token.pkl
        run: echo "${{ secrets.TOKEN_PKL }}" | base64 --decode > token.pkl

      - name: Publish to Blogger
        run: python scripts/publish_to_blogger.py
        env:
          BLOG_ID: ${{ secrets.BLOGGER_BLOG_ID }}
          TOKEN_FILE: token.pkl

      - name: Push updated published_posts.json to gh-pages
        run: |
          # Клонируем gh-pages в отдельную временную директорию
          TMP_DIR=$(mktemp -d)
          git clone --branch gh-pages https://x-access-token:${{ secrets.PAT_TOKEN }}@github.com/${{ github.repository }}.git "$TMP_DIR"

          # Копируем файл published_posts.json
          cp published_posts.json "$TMP_DIR/published_posts.json"

          cd "$TMP_DIR"

          # Настраиваем имя и email для коммитов в этом репозитории
          git config user.name "github-actions[bot]"
          git config user.email "github-actions[bot]@users.noreply.github.com"

          # Коммитим и пушим
          git add published_posts.json
          git commit -m "Update published_posts.json" || echo "No changes to commit"
          git push origin gh-pages
