name: Sync to Hugging Face

on:
  push:
    branches:
      - main

jobs:
  sync:
    runs-on: ubuntu-latest

    steps:
      - name: Checkout GitHub repo
        uses: actions/checkout@v3

      - name: Set up Git identity
        run: |
          git config --global user.email "bot@github.com"
          git config --global user.name "GitHub Actions"

      - name: Clone Hugging Face repo
        run: |
          git clone https://kagvi13:${{ secrets.HF_TOKEN }}@huggingface.co/kagvi13/HMP hf_repo

      - name: Sync files (excluding .git, .github)
        run: |
          rsync -av --exclude='.git' --exclude='.github' --exclude='.gitignore' ./ hf_repo/

      - name: Commit and push to Hugging Face
        run: |
          cd hf_repo
          git add .
          git diff --quiet && git diff --staged --quiet || git commit -m "Sync from GitHub"
          git push
