      - name: Clone Hugging Face repo
        run: git clone https://kagvi13:${{ secrets.HF_TOKEN }}@huggingface.co/kagvi13/HMP hf_repo

      - name: Install Git LFS
        run: |
          sudo apt-get update
          sudo apt-get install git-lfs
          git lfs install

      - name: Sync files excluding .git and .github
        run: rsync -av --exclude='.git' --exclude='.github' ./ hf_repo/

      - name: Commit and push changes
        run: |
          cd hf_repo
          git config user.email "action@github.com"
          git config user.name "GitHub Action"
          git add .
          git lfs track "*.png"
          git commit -m "Sync from GitHub with LFS" || echo "Nothing to commit"
          git push
